-- 코드를 입력하세요
select DISTINCT CH.CAR_ID, 
    CC.CAR_TYPE, FLOOR(CC.DAILY_FEE*30*(1-CP.DISCOUNT_RATE/100)) FEE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH JOIN
    CAR_RENTAL_COMPANY_CAR AS CC ON CH.CAR_ID = CC.CAR_ID JOIN
    # '30일 이상' 조건만 on에서 필터링
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP ON CC.CAR_TYPE = CP.CAR_TYPE AND CP.DURATION_TYPE = '30일 이상'
WHERE 
    # suv랑 세단만 필터링
    CC.CAR_TYPE IN ('SUV','세단') AND
    # 11월 한달 동안 대여가능한 car_id 필터링 
    CH.CAR_ID NOT IN 
        #11월 대여 불가능한 car_id 서브쿼리
        (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE 
        MONTH(START_DATE) = 11 OR MONTH(END_DATE) = 11 OR
            ('2022-11-01' BETWEEN START_DATE AND END_DATE))
    # 50~200만원 요금 조건 필터링
    AND
    FLOOR(CC.DAILY_FEE*30*(100-CP.DISCOUNT_RATE)/100)>=500000 AND
    FLOOR(CC.DAILY_FEE*30*(100-CP.DISCOUNT_RATE)/100)<2000000
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;

# SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE 
# MONTH(START_DATE) = 11 OR MONTH(END_DATE) = 11 OR
#     ('2022-11-01' BETWEEN START_DATE AND END_DATE);