-- 코드를 입력하세요
select DISTINCT CH.CAR_ID, 
    CC.CAR_TYPE, FLOOR(CC.DAILY_FEE*30*(1-CP.DISCOUNT_RATE/100)) FEE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH JOIN
    CAR_RENTAL_COMPANY_CAR AS CC ON CH.CAR_ID = CC.CAR_ID JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CP ON CC.CAR_TYPE = CP.CAR_TYPE AND CP.DURATION_TYPE = '30일 이상'
WHERE CC.CAR_TYPE IN ('SUV','세단') AND
    CH.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE 
        MONTH(START_DATE) = 11 OR MONTH(END_DATE) = 11 OR
            ('2022-11-01' BETWEEN START_DATE AND END_DATE))
    AND
    FLOOR(CC.DAILY_FEE*30*(100-CP.DISCOUNT_RATE)/100)>=500000 AND
    FLOOR(CC.DAILY_FEE*30*(100-CP.DISCOUNT_RATE)/100)<2000000
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;

# SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE 
# MONTH(START_DATE) = 11 OR MONTH(END_DATE) = 11 OR
#     ('2022-11-01' BETWEEN START_DATE AND END_DATE);