-- 코드를 입력하세요
SELECT
    sub.HISTORY_ID HISTORY_ID
    , ROUND(IF(sub.DURATION_TYPE is null,sub.daily_fee*sub.DURATION,sub.daily_fee*sub.DURATION*(100-DP.DISCOUNT_RATE)/100),0)
    AS FEE
FROM
    (SELECT 
        RH.*
        , CASE
            WHEN DATEDIFF(RH.END_DATE,RH.START_DATE)+1 >= 90 THEN '90일 이상' 
            WHEN DATEDIFF(RH.END_DATE,RH.START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(RH.END_DATE,RH.START_DATE)+1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
        , DATEDIFF(RH.END_DATE,RH.START_DATE)+1 DURATION
        , C.CAR_TYPE
        , C.DAILY_FEE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY RH JOIN 
        CAR_RENTAL_COMPANY_CAR C ON RH.CAR_ID = C.CAR_ID )sub 
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON sub.CAR_TYPE = DP.CAR_TYPE and sub.DURATION_TYPE = DP.DURATION_TYPE
WHERE sub.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
;

