-- 코드를 작성해주세요

select 
    e.DEPT_ID
    , d.DEPT_NAME_EN
    , ROUND(AVG(e.SAL),0)AS AVG_SAL
from
    HR_EMPLOYEES e join HR_DEPARTMENT d on e.DEPT_ID = d.DEPT_ID
GROUP BY e.DEPT_ID,d.DEPT_NAME_EN
ORDER BY AVG_SAL DESC
;